import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
	// Define variables to store string values
	const url = 'https://automationexercise.com/';
	const signupLinkText = ' Signup / Login';
	const namePlaceholder = 'adas';
	const emailAddress = 'adas11nov@yopmail.com';
	const signupButtonText = 'Signup';
	const titleLabel = 'Mr.';
	const password = 'Adas#123';
	const birthDay = '12';
	const birthMonth = '5';
	const birthYear = '2018';
	const newsletterCheckboxLabel = 'Sign up for our newsletter!';
	const specialOffersCheckboxLabel = 'Receive special offers from';
	const firstName = 'adas';
	const lastName = 'das';
	const companyName = 'aaa';
	const address1 = 'myaddress1';
	const address2 = 'myaddress2';
	const state = 'WB';
	const city = 'Kolkata';
	const zipcode = '700091';
	const mobileNumber = '9876543210';
	const accountCreatedHeading = 'Account Created!';
	const congratulationsText = 'Congratulations! Your new';
	const continueButtonText = 'Continue';
	const loggedInText = 'Logged in as adas';
	const logoutLinkText = ' Logout';

	// Use the variables in the function
	await page.goto(url);
	await page.getByRole('link', { name: signupLinkText }).click();
	await page.getByPlaceholder('Name').fill(namePlaceholder);
	await page.locator('form').filter({ hasText: signupButtonText }).getByPlaceholder('Email Address').fill(emailAddress);
	await page.getByRole('button', { name: signupButtonText }).click();
	await page.getByLabel(titleLabel).check();
	await page.getByLabel('Password *').fill(password);
	await page.locator('#days').selectOption(birthDay);
	await page.locator('#months').selectOption(birthMonth);
	await page.locator('#years').selectOption(birthYear);
	await page.getByLabel(newsletterCheckboxLabel).check();
	await page.getByLabel(specialOffersCheckboxLabel).check();
	await page.getByLabel('First name *').fill(firstName);
	await page.getByLabel('Last name *').fill(lastName);
	await page.getByLabel('Company', { exact: true }).fill(companyName);
	await page.getByLabel('Address * (Street address, P.').fill(address1);
	await page.getByLabel('Address 2').fill(address2);
	await page.getByLabel('State *').fill(state);
	await page.getByLabel('City *').fill(city);
	await page.locator('#zipcode').fill(zipcode);
	await page.getByLabel('Mobile Number *').fill(mobileNumber);
	await page.getByRole('button', { name: 'Create Account' }).click();
	await page.getByRole('heading', { name: accountCreatedHeading }).click();
	await page.getByText(accountCreatedHeading).click();
	await page.getByText(congratulationsText).click();
	await page.getByRole('link', { name: continueButtonText }).click();
	await page.getByText(loggedInText).click();
	await page.getByRole('link', { name: logoutLinkText }).click();
});